#!/usr/bin/env python3

"""Guess the capital of Panama | Shalese
    Mini Project 1"""


round = 0            # integer round initiated to 0
while True:          # sets up infinite loop condition
    round = round + 1       # increase the round counter

    # print question
    print("What is the capital of Panama?")

    # collect user input
    answer = input("Answer: ")

    # test logic with the `if` statement
    # what to do if this statement is found to be true
    if answer == "Panama City":
        print("You are correct!")
        break         # escape while loop
    elif answer == "panama city":
        print("You're close, use correct punctuation")
    elif answer != "Panama City":
        print("Incorrect, try again")
    else:
        print("Incorrect")
        break         # escape while loop

