#!usr/bin/env python3

"""Alta3 Challenge | Shalese C
        Dracula"""

# read the content of the novel
foo= open("dracula.txt","r")
    

# loop over every line and count
count= 0
for line in foo:
    if "vampire" in line.lower():
        count += 1
        print(line)

foo.close()
    


